****NETFLIX DATA ANALYSIS (csv FILE)****

In [217]:
import numpy as npa
import pandas as pd

**IMPORT CSV fILE**

In [175]:
df = pd.read_csv("Datasets/netflix_titles.csv")

**INSPECTING DATASETS**

In [176]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [177]:
df.shape

(8807, 12)

In [ ]:
df.info()  #some missig values exists.

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

***SELECTION OF DATA***

In [179]:
df["title"]

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: str

In [180]:
df[['type', 'cast']]

         type                                               cast
0       Movie                                                NaN
1     TV Show  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2     TV Show  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3     TV Show                                                NaN
4     TV Show  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
...       ...                                                ...
8802    Movie  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8803  TV Show                                                NaN
8804    Movie  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805    Movie  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806    Movie  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

[8807 rows x 2 columns]

In [181]:
df[['type', 'cast']].size

17614

In [182]:
df[['type','director','cast', 'country']]

,type,director,cast,country
0,Movie,Kirsten Johnson,NaN,United States
1,TV Show,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa
2,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN
3,TV Show,NaN,NaN,NaN
4,TV Show,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India
...,...,...,...,...
8802,Movie,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States
8803,TV Show,NaN,NaN,NaN
8804,Movie,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States
8805,Movie,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States
8806,Movie,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India

In [183]:
df.head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
14,s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
19,s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."

In [184]:
df[df['type']=='Movie']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [185]:
df[df['type']=='Movie'].shape

(6131, 12)

In [186]:
df[df['type']=='TV Show']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [187]:
df[df['type']=='TV Show'].shape

(2676, 12)

In [188]:
df[df['type']=='TV Show'].info

<bound method DataFrame.info of      show_id     type                  title         director  \
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
5         s6  TV Show          Midnight Mass    Mike Flanagan
...      ...      ...                    ...              ...
8795   s8796  TV Show        Yu-Gi-Oh! Arc-V              NaN
8796   s8797  TV Show             Yunus Emre              NaN
8797   s8798  TV Show              Zak Storm              NaN
8800   s8801  TV Show     Zindagi Gulzar Hai              NaN
8803   s8804  TV Show            Zombie Dumb              NaN

                                                   cast  \
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                                   NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
5     Kate Siegel, Zach Gilford, Hamish Linklater, H...
...                                                 ...
8795  Mike Liscio, Emily Bauer, Billy Bob Thompson, ...
8796  Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...
8797  Michael Johnston, Jessica Gee-George, Christin...
8800  Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...
8803                                                NaN

                                            country          date_added  \
1                                      South Africa  September 24, 2021
2                                               NaN  September 24, 2021
3                                               NaN  September 24, 2021
4                                             India  September 24, 2021
5                                               NaN  September 24, 2021
...                                             ...                 ...
8795                                  Japan, Canada         May 1, 2018
8796                                         Turkey    January 17, 2017
8797  United States, France, South Korea, Indonesia  September 13, 2018
8800                                       Pakistan   December 15, 2016
8803                                            NaN        July 1, 2019

      release_year rating   duration  \
1             2021  TV-MA  2 Seasons
2             2021  TV-MA   1 Season
3             2021  TV-MA   1 Season
4             2021  TV-MA  2 Seasons
5             2021  TV-MA   1 Season
...            ...    ...        ...
8795          2015  TV-Y7  2 Seasons
8796          2016  TV-PG  2 Seasons
8797          2016  TV-Y7  3 Seasons
8800          2012  TV-PG   1 Season
8803          2018  TV-Y7  2 Seasons

                                              listed_in  \
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
5                    TV Dramas, TV Horror, TV Mysteries
...                                                 ...
8795                             Anime Series, Kids' TV
8796                  International TV Shows, TV Dramas
8797                                           Kids' TV
8800  International TV Shows, Romantic TV Shows, TV ...
8803             Kids' TV, Korean TV Shows, TV Comedies

                                            description
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
5     The arrival of a charismatic young priest brin...
...                                                 ...
8795  Now that he's discovered the Pendulum Summonin...
8796  During the Mongol invasions, Yunus Emre leaves...
8797  Teen surfer Zak Storm is mysteriously transpor...
8800  Strong-willed, middle-class Kashaf and carefre...
8803  While living alone in a spooky town, a young g...

[2676 rows x 12 columns]>

In [189]:
df[df['release_year']>= 2020]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
7594,s7595,Movie,Norm of the North: Family Vacation,Anthony Bell,"Andrew Toth, Lisa Durupt, Jonathan Holmes, Pau...",United States,"May 25, 2020",2020,TV-Y7,89 min,Children & Family Movies,"Stressed by his duties as king and father, Nor..."
8099,s8100,Movie,Straight Up,James Sweeney,"James Sweeney, Katie Findlay, Randall Park, Hi...",United States,"June 26, 2020",2020,TV-MA,96 min,"Comedies, Independent Movies, LGBTQ Movies",When a gay brainiac with OCD questions his ide...
8125,s8126,TV Show,Super Wings,NaN,"Luca Padovan, Evan Smolin, Junah Jang, Colin C...","United States, South Korea, China","December 1, 2020",2020,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows",A cheerful jet and his transforming pals striv...
8132,s8133,TV Show,Surviving R. Kelly Part II: The Reckoning,NaN,R. Kelly,United States,"April 13, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",As more women come forward with harrowing accu...
8437,s8438,TV Show,The Netflix Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",United States,"January 2, 2021",2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."

In [190]:
df[df['release_year']>= 2020].shape

(1545, 12)

In [191]:
df[(df['release_year']>= 2020) & (df['type']=='Movie')]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
...,...,...,...,...,...,...,...,...,...,...,...,...
3046,s3047,Movie,All the Freckles in the World,Yibrán Asuad,"Hánssel Casillas, Loreto Peralta, Andrea Sutto...",Mexico,"January 3, 2020",2020,TV-14,90 min,"Comedies, International Movies, Romantic Movies",Thirteen-year-old José Miguel is immune to 199...
3060,s3061,Movie,Ghost Stories,"Anurag Kashyap, Dibakar Banerjee, Karan Johar,...","Janhvi Kapoor, Sobhita Dhulipala, Sukant Goel,...",India,"January 1, 2020",2020,TV-MA,145 min,"Horror Movies, International Movies, Thrillers","The directors of Emmy-nominated ""Lust Stories""..."
5972,s5973,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...
7594,s7595,Movie,Norm of the North: Family Vacation,Anthony Bell,"Andrew Toth, Lisa Durupt, Jonathan Holmes, Pau...",United States,"May 25, 2020",2020,TV-Y7,89 min,Children & Family Movies,"Stressed by his duties as king and father, Nor..."
8099,s8100,Movie,Straight Up,James Sweeney,"James Sweeney, Katie Findlay, Randall Park, Hi...",United States,"June 26, 2020",2020,TV-MA,96 min,"Comedies, Independent Movies, LGBTQ Movies",When a gay brainiac with OCD questions his ide...

In [192]:
movies_2020 = df[(df['release_year']>= 2020) & (df['type']=='Movie')].shape ## 794 movies released after 2020
print("number of Movies released after 2020: ", movies_2020)

number of Movies released after 2020:  (794, 12)

***MISSING VALUES IN DATASET***

In [193]:
df.info  # THE INFO TELLS US THERE ARE MISSING VALUES IN CERTAIN NUMBER OF COLUMNS

<bound method DataFrame.info of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]>

In [194]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [195]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [196]:
df.isna().sum().sort_values(ascending=False) # Column named as DIRECTOR has the highest number of missing values

director        2634
country          831
cast             825
date_added        10
rating             4
duration           3
show_id            0
type               0
title              0
release_year       0
listed_in          0
description        0
dtype: int64

In [197]:
df.isna().sum().idxmax() # Name of the colummn with the  highest number of missing values

'director'

In [198]:
df.dropna(subset=['country'])

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [199]:
df.dropna(subset=['country']).shape

(7976, 12)

In [200]:
df.sort_values(by='release_year',ascending=False) #NEWEST CONTENT

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
31,s32,TV Show,Chicago Party Aunt,NaN,"Lauren Ash, Rory O'Malley, RuPaul Charles, Jil...",NaN,"September 17, 2021",2021,TV-MA,1 Season,TV Comedies,Chicago Party Aunt Diane is an idolized troubl...
30,s31,Movie,Ankahi Kahaniya,"Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket C...","Abhishek Banerjee, Rinku Rajguru, Delzad Hiwal...",NaN,"September 17, 2021",2021,TV-14,111 min,"Dramas, Independent Movies, International Movies","As big city life buzzes around them, lonely so..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

In [201]:
df.sort_values(by='release_year',ascending=True) #OLDEST CONTENT

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
...,...,...,...,...,...,...,...,...,...,...,...,...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
68,s69,Movie,Schumacher,"Hanns-Bruno Kammertöns, Vanessa Nöcker, Michae...",Michael Schumacher,NaN,"September 15, 2021",2021,TV-14,113 min,"Documentaries, International Movies, Sports Mo...",Through exclusive interviews and archival foot...

***CREATING COLUMNS***

In [202]:

df["Recently_released"] = df["release_year"] >= 2020

In [203]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

***GROUPBY OPERATIONS***

In [204]:
df.groupby('type')['release_year'].mean()

type
Movie      2013.121514
TV Show    2016.605755
Name: release_year, dtype: float64

In [205]:
df.groupby('country').size()

country
, France, Algeria                                       1
, South Korea                                           1
Argentina                                              56
Argentina, Brazil, France, Poland, Germany, Denmark     1
Argentina, Chile                                        2
                                                       ..
Venezuela                                               1
Venezuela, Colombia                                     1
Vietnam                                                 7
West Germany                                            1
Zimbabwe                                                1
Length: 748, dtype: int64

In [206]:
df.groupby('type').size()

type
Movie      6131
TV Show    2676
dtype: int64

In [207]:
df.groupby('type')['release_year'].mean()

type
Movie      2013.121514
TV Show    2016.605755
Name: release_year, dtype: float64

In [208]:
df.groupby('rating')['title'].count()

rating
66 min         1
74 min         1
84 min         1
G             41
NC-17          3
NR            80
PG           287
PG-13        490
R            799
TV-14       2160
TV-G         220
TV-MA       3207
TV-PG        863
TV-Y         307
TV-Y7        334
TV-Y7-FV       6
UR             3
Name: title, dtype: int64

In [209]:
df.groupby('country')['title'].count().sort_values(ascending=False).head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: title, dtype: int64

***STRING OPERATIONS***

In [210]:
df['title'].str.upper()

0        DICK JOHNSON IS DEAD
1               BLOOD & WATER
2                   GANGLANDS
3       JAILBIRDS NEW ORLEANS
4                KOTA FACTORY
                ...
8802                   ZODIAC
8803              ZOMBIE DUMB
8804               ZOMBIELAND
8805                     ZOOM
8806                   ZUBAAN
Name: title, Length: 8807, dtype: str

In [211]:
df['title'].str.lower()

0        dick johnson is dead
1               blood & water
2                   ganglands
3       jailbirds new orleans
4                kota factory
                ...
8802                   zodiac
8803              zombie dumb
8804               zombieland
8805                     zoom
8806                   zubaan
Name: title, Length: 8807, dtype: str

In [212]:
df[df['title'].str.contains('love', case=False, na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Recently_released
25,s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell,Australia,"September 21, 2021",2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...,True
158,s159,Movie,Love Don't Cost a Thing,Troy Byer,"Nick Cannon, Christina Milian, Kenan Thompson,...",United States,"September 1, 2021",2003,PG-13,101 min,"Comedies, Romantic Movies",A nerdy teen tries to make himself cool by ass...,False
159,s160,Movie,Love in a Puff,Pang Ho-cheung,"Miriam Chin Wah Yeung, Shawn Yue, Singh Hartih...",Hong Kong,"September 1, 2021",2010,TV-MA,103 min,"Comedies, Dramas, International Movies",When the Hong Kong government enacts a ban on ...,False
206,s207,Movie,"LSD: Love, Sex Aur Dhokha",Dibakar Banerjee,"Nushrat Bharucha, Anshuman Jha, Neha Chauhan, ...",India,"August 27, 2021",2010,TV-MA,112 min,"Dramas, Independent Movies, International Movies",This provocative drama examines how the voyeur...,False
227,s228,Movie,Really Love,Angel Kristi Williams,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,"August 25, 2021",2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8567,s8568,TV Show,The Year of Happiness and Love,NaN,"Amber Kuo, James Wen, Weber Yang, Sonia Sui, N...",Taiwan,"September 1, 2016",2009,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Jiang Chen-bo is a loser without prospects for...,False
8575,s8576,TV Show,This Is My Love,NaN,"Jin-mo Joo, Sa-rang Kim, Junior, Ja-in Lee, Su...",South Korea,"May 22, 2017",2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A renowned actor who is still pining over the ...,False
8649,s8650,Movie,Two Lovers and a Bear,Kim Nguyen,"Dane DeHaan, Tatiana Maslany, Gordon Pinsent, ...",Canada,"May 2, 2017",2016,R,95 min,"Dramas, Independent Movies, Romantic Movies",A troubled couple living near the North Pole b...,False
8721,s8722,TV Show,What Is Love?,NaN,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,"January 1, 2017",2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...,False
8725,s8726,Movie,What's Up With Love?,"Rudy Soedjarwo, Riri Riza","Dian Sastrowardoyo, Nicholas Saputra, Ladya Ch...",Indonesia,"December 8, 2018",2002,R,110 min,"Dramas, International Movies, Romantic Movies",A popular high school girl strains her relatio...,False

In [213]:
df[df['title'].str.contains(r'\bking\b', case=False, na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Recently_released
73,s74,Movie,King of Boys,Kemi Adetiba,"Sola Sobowale, Adesua Etomi, Remilekun ""Remini...",Nigeria,"September 14, 2021",2018,TV-MA,182 min,"Dramas, International Movies",When a powerful businesswoman’s political ambi...,False
198,s199,TV Show,King of Boys: The Return of the King,Kemi Adetiba,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,"August 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...,True
291,s292,TV Show,SHAMAN KING,NaN,"Yoko Hikasa, Katsuyuki Konishi, Megumi Hayashi...",Japan,"August 9, 2021",2021,TV-14,1 Season,"Anime Series, International TV Shows",Medium Yoh Asakura enters a battle tournament ...,True
627,s628,TV Show,The Daily Life of the Immortal King,NaN,"Sun Lulu, Qian Chen, Gu Jiangshan",China,"June 30, 2021",2020,TV-14,1 Season,"Anime Series, International TV Shows, Teen TV ...","Having vanquished a powerful demon at age six,...",True
815,s816,Movie,The Girl King,Mika Kaurismäki,"Malin Buska, Sarah Gadon, Michael Nyqvist, Luc...",NaN,"June 2, 2021",2015,TV-MA,106 min,"Dramas, International Movies, LGBTQ Movies",Sweden's forward-thinking Queen Kristina resis...,False
1010,s1011,Movie,Rudra: The Rise of King Pharaoh,NaN,"Shailendra Pandey, Rohan, Mukesh Pandey, Bhakt...",NaN,"April 20, 2021",2019,TV-Y7,91 min,Children & Family Movies,"When a malicious, resurrected mummy begins to ...",False
2665,s2666,TV Show,The King: Eternal Monarch,NaN,"Lee Min-ho, Kim Go-eun, Woo Do‑hwan, Kim Kyung...",South Korea,"April 18, 2020",2020,TV-14,1 Season,"Crime TV Shows, International TV Shows, Korean...",A modern-day Korean emperor passes through a m...,True
2794,s2795,TV Show,The Letter for the King,NaN,"Amir Wilson, Ruby Ashbourne Serkis, Thaddea Gr...",United Kingdom,"March 20, 2020",2020,TV-PG,1 Season,"British TV Shows, International TV Shows, TV A...",A young knight in training contends with ancie...,True
2795,s2796,TV Show,"Tiger King: Murder, Mayhem and Madness","Eric Goode, Rebecca Chaiklin",NaN,United States,"March 20, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",A zoo owner spirals out of control amid a cast...,True
3347,s3348,Movie,The King,David Michôd,"Timothée Chalamet, Joel Edgerton, Robert Patti...","United Kingdom, Hungary, Australia","November 1, 2019",2019,R,141 min,Dramas,Wayward Prince Hal must turn from carouser to ...,False
3585,s3586,TV Show,The King's Avatar,NaN,"Yang Yang, Jiang Shuying, Lai Yumeng, Li Muche...",China,"August 16, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,...",When an elite gamer is forced out of his profe...,False
3842,s3843,Movie,Gatao 2: Rise of the King,Yen Cheng-kuo,"Collin Chou, Jason Wang, Jack Kao, Tsai Chen-n...",Taiwan,"May 9, 2019",2018,TV-MA,126 min,"Action & Adventure, Dramas, International Movies",When a zealous gang leader plans to take out a...,False
4091,s4092,Movie,The Drug King,Woo Min-ho,"Song Kang-ho, Cho Jung-seok, Bae Doona, Kim So...",South Korea,"February 21, 2019",2018,TV-MA,139 min,"Dramas, International Movies, Thrillers",A petty smuggler from Busan dives headfirst in...,False
4247,s4248,Movie,Tim Minchin: So F**king Rock,Matt Askem,Tim Minchin,United Kingdom,"December 31, 2018",2008,TV-MA,127 min,"Music & Musicals, Stand-Up Comedy",Comedic pianist Tim Minchin performs a host of...,False
4404,s4405,Movie,Outlaw King,David Mackenzie,"Chris Pine, Aaron Taylor-Johnson, Florence Pug...","United Kingdom, United States","November 9, 2018",2018,R,122 min,"Action & Adventure, Dramas","In 14th-century Scotland, Robert the Bruce cla...",False
4480,s4481,Movie,Ronnie Coleman: The King,Vlad Yudin,Ronnie Coleman,United States,"October 25, 2018",2018,TV-MA,93 min,Documentaries,"Today, legendary bodybuilder Ronnie Coleman's ...",False
4484,s4485,Movie,Scorpion King 5: Book of Souls,Don Michael Paul,"Zach McGowan, Pearl Thusi, Nathan Jones, Peter...",United States,"October 23, 2018",2018,PG-13,102 min,"Action & Adventure, Sci-Fi & Fantasy",The Scorpion King joins forces with a Nubian p...,False
4789,s4790,Movie,King of Peking,Sam Voutas,"Zhao Jun, Wang Naixun, Han Qing, Si Chao, Geng...","China, United States, Australia","July 2, 2018",2018,TV-14,88 min,"Comedies, Dramas, International Movies","Strapped for cash, a traveling projectionist b...",False
4838,s4839,TV Show,Dinosaur King,NaN,"Megumi Matsumoto, Matsuri Mizuguchi, Tomoko Ko...",Japan,"June 2, 2018",2008,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Aided by tablets found near a downed meteorite...,False
4879,s4880,TV Show,Kong: King of the Apes,NaN,"Lee Tockar, Sam Vincent, Alessandro Juliani, T...","United States, Japan, Canada","May 4, 2018",2018,TV-Y7,2 Seasons,Kids' TV,"In 2050, an evil scientist is about to unleash...",False
5084,s5085,Movie,The Polka King,Maya Forbes,"Jack Black, Jenny Slate, Jason Schwartzman, Ja...",United States,"January 12, 2018",2018,TV-14,94 min,"Comedies, Independent Movies","Determined to make it big in America, Polish-b...",False
5138,s5139,TV Show,All Hail King Julien,NaN,"Danny Jacobs, Andy Richter, Henry Winkler, Kev...",United States,"December 1, 2017",2017,TV-Y7,5 Seasons,"Kids' TV, TV Comedies",In this Emmy winner for Outstanding Children's...,False
5344,s5345,Movie,Message from the King,Fabrice Du Welz,"Chadwick Boseman, Luke Evans, Teresa Palmer, A...","United Kingdom, France, Belgium, United States","August 4, 2017",2017,R,103 min,"Independent Movies, Thrillers",On a relentless quest to avenge his sister's m...,False
5383,s5384,TV Show,King’s War,NaN,"Chen Daoming, Peter Ho, Duan Yihong, Qin Lan, ...",China,"July 7, 2017",2012,TV-14,1 Season,"International TV Shows, TV Dramas","In 210 B.C., during the upheaval following the...",False
5475,s5476,Movie,Hasan Minhaj: Homecoming King,Christopher Storer,Hasan Minhaj,NaN,"May 23, 2017",2017,TV-MA,73 min,Stand-Up Comedy,"Comic Hasan Minhaj of ""The Daily Show"" shares ...",False
5488,s5489,TV Show,All Hail King Julien: Exiled,NaN,"Danny Jacobs, Andy Richter, Kevin Michael Rich...",NaN,"May 12, 2017",2017,TV-Y7,1 Season,"Kids' TV, TV Action & Adventure, TV Comedies","Julien's been dethroned, but loyal friends and...",False
5511,s5512,Movie,Rodney King,Spike Lee,Roger Guenveur Smith,United States,"April 28, 2017",2017,TV-MA,53 min,Dramas,Roger Guenveur Smith gives voice to the man at...,False
5747,s5748,Movie,Berserk: The Golden Age Arc I - The Egg of the...,Toshiyuki Kubooka,"Hiroaki Iwanaga, Takahiro Sakurai, Toa Yukinar...",Japan,"October 15, 2016",2012,TV-MA,77 min,"Action & Adventure, Anime Features, Internatio...",Loner Guts is recruited by Griffith and his ba...,False
5765,s5766,Movie,Chatô: The King of Brazil,Guilherme Fontes,"Marco Ricca, Andrea Beltrão, Letícia Sabatella...",Brazil,"October 1, 2016",2015,TV-MA,105 min,"Dramas, International Movies",The romanticized life of media mogul Assis Cha...,False
5816,s5817,Movie,Jim Gaffigan: King Baby,Troy Miller,Jim Gaffigan,United States,"August 11, 2016",2009,TV-PG,71 min,Stand-Up Comedy,"Jim Gaffigan offers up his take on bacon, bowl...",False
5953,s5954,Movie,Joseph: King of Dreams,"Rob LaDuca, Robert C. Ramirez","Ben Affleck, Mark Hamill, Richard Herd, Mauree...","United States, France, United Kingdom","September 27, 2011",2000,TV-PG,75 min,"Children & Family Movies, Dramas, Faith & Spir...",With his gift of dream interpretation and his ...,False
7207,s7208,Movie,King Jack,Felix Thompson,"Charlie Plummer, Cory Nichols, Christian Madse...",United States,"July 1, 2016",2015,NR,81 min,"Dramas, Independent Movies","Already coping with a bully, a mercurial older...",False
7208,s7209,Movie,King's Ransom,Jeffrey W. Byrd,"Anthony Anderson, Jay Mohr, Kellita Smith, Nic...","United States, Canada","November 1, 2019",2005,PG-13,98 min,"Action & Adventure, Comedies","A wealthy, despicable businessman comes to the...",False
7513,s7514,Movie,Motu Patlu: King of Kings,Suhas Kadav,"Saurav Chakrabarty, Vinay Pathak",India,"July 6, 2017",2016,TV-Y7-FV,109 min,"Children & Family Movies, Comedies",Motu and Patlu want to help a circus lion get ...,False
7596,s7597,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,False
7689,s7690,TV Show,P. King Duckling,NaN,"Marc Thompson, Benjie Randall, Courtney Shaw",United States,"November 7, 2017",2016,TV-Y,1 Season,"Kids' TV, TV Comedies","P. King, the daring but hapless duck, teams up...",False
8370,s8371,Movie,The Jack King Affair,"Benjamin Cohen, Nicolas Cotto",NaN,France,"January 2, 2018",2015,TV-14,52 min,"Documentaries, International Movies",This documentary explores a bold World War II ...,False
8377,s8378,Movie,The King's Speech,Tom Hooper,"Colin Firth, Geoffrey Rush, Helena Bonham Cart...","United Kingdom, United States, Australia","June 2, 2018",2010,R,118 min,"Dramas, International Movies","In this biographical drama, Britain's King Geo...",False
8404,s8405,Movie,The Lord of the Rings: The Return of the King,Peter Jackson,"Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mo...","New Zealand, United States","January 1, 2020",2003,PG-13,201 min,"Action & Adventure, Sci-Fi & Fantasy",Aragorn is revealed as the heir to the ancient...,False
8412,s8413,Movie,The Man Who Would Be Polka King,"John Mikulak, Joshua Brown","Jan Lewan, Greg Korin",United States,"January 12, 2018",2009,TV-14,68 min,"Documentaries, Music & Musicals",This irreverent documentary reveals how charmi...,False

In [214]:
df['director'].str.strip()

0       Kirsten Johnson
1                   NaN
2       Julien Leclercq
3                   NaN
4                   NaN
             ...
8802      David Fincher
8803                NaN
8804    Ruben Fleischer
8805       Peter Hewitt
8806        Mozez Singh
Name: director, Length: 8807, dtype: str

In [215]:
df.groupby('release_year').size().sort_values(ascending=False).head(1)

release_year
2018    1147
dtype: int64

***TOP 20 NEWEST RELEASED MOVIES OF INDIA***

In [216]:
df[df['country']=='India'].sort_values(by='release_year', ascending=False).head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Recently_released
190,s191,Movie,Thimmarusu,Sharan Koppisetty,"Satya Dev, Priyanka Jawalkar, Brahmaji",India,"August 28, 2021",2021,TV-14,125 min,"Dramas, International Movies",Eight years after a young man is framed for mu...,True
909,s910,Movie,Milestone,Ivan Ayr,"Suvinder Vicky, Lakshvir Saran, Mohinder Gujra...",India,"May 7, 2021",2021,TV-14,98 min,"Dramas, Independent Movies, International Movies","Recently marking 500,000 kilometers on the roa...",True
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,True
959,s960,Movie,The Disciple,Chaitanya Tamhane,"Aditya Modak, Arun Dravid, Sumitra Bhave, Deep...",India,"April 30, 2021",2021,TV-MA,128 min,"Dramas, Independent Movies, International Movies","Self-doubt, sacrifice and struggle converge in...",True
918,s919,TV Show,Lava Ka Dhaava,NaN,"Jaaved Jaaferi, Rutledge Wood",India,"May 5, 2021",2021,TV-PG,1 Season,Reality TV,Actor Jaaved Jaafferi brings his signature hum...,True
297,s298,TV Show,Navarasa,"Bejoy Nambiar, Priyadarshan, Karthik Narain, V...","Suriya, Vijay Sethupathi, Revathy, Prakash Raj...",India,"August 6, 2021",2021,TV-MA,1 Season,TV Shows,"From amusement to awe, the nine human emotions...",True
903,s904,Movie,Nayattu,Martin Prakkat,"Kunchacko Boban, Joju George, Nimisha Sajayan,...",India,"May 9, 2021",2021,TV-MA,122 min,"Dramas, International Movies, Thrillers",Three police officers become pawns for unscrup...,True
877,s878,Movie,Cinema Bandi,Praveen Kandregula,"Vikas Vasistha, Sandeep Varanasi, Rag Mayur, T...",India,"May 14, 2021",2021,TV-MA,99 min,"Comedies, Independent Movies, International Mo...",A struggling rickshaw driver’s life takes a ro...,True
876,s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...,True
735,s736,Movie,Sarbath,Prabhakaran,"Kathir, Soori, Rahasya Gorak, Ashvatt",India,"June 11, 2021",2021,TV-PG,113 min,"Comedies, Dramas, International Movies",When a city man returns to his native village ...,True
850,s851,Movie,99 Songs,Vishwesh Krishnamoorthy,"Ehan Bhat, Edilsy Vargas, Manisha Koirala, Lis...",India,"May 21, 2021",2021,TV-14,131 min,"Dramas, International Movies, Music & Musicals",Challenged to compose 100 songs before he can ...,True
871,s872,Movie,Sardar Ka Grandson,Kaashvie Nair,"Arjun Kapoor, Neena Gupta, Rakul Preet Singh, ...",India,"May 18, 2021",2021,TV-14,140 min,"Comedies, Dramas, International Movies",A devoted grandson’s mission to reunite his ai...,True
551,s552,Movie,Haseen Dillruba,Vinil Mathew,"Taapsee Pannu, Vikrant Massey, Harshvardhan Ra...",India,"July 2, 2021",2021,TV-MA,136 min,"International Movies, Romantic Movies, Thrillers",Under investigation as a suspect in her husban...,True
1093,s1094,TV Show,The Big Day,NaN,NaN,India,"April 7, 2021",2021,TV-14,2 Seasons,"International TV Shows, Reality TV, Romantic T...","For six engaged couples, happily ever after be...",True
1098,s1099,Movie,Mandela,Madonne Ashwin,"Yogi Babu, Sheela Rajkumar, Sangili Murugan, G...",India,"April 5, 2021",2021,TV-14,140 min,"Comedies, Dramas, International Movies",Amid a local election with two rivals vying to...,True
1108,s1109,Movie,Irul,Naseef Yusuf Izuddin,"Fahadh Faasil, Soubin Shahir, Darshana Rajendran",India,"April 2, 2021",2021,TV-MA,91 min,"International Movies, Thrillers",When a car breakdown forces a couple to seek s...,True
1087,s1088,Movie,Roohi,Hardik Mehta,"Rajkummar Rao, Varun Sharma, Janhvi Kapoor, Ma...",India,"April 9, 2021",2021,TV-14,133 min,"Comedies, Horror Movies, International Movies","Hired to kidnap a bride, two bumbling pals fac...",True
998,s999,Movie,Searching For Sheela,NaN,Ma Anand Sheela,India,"April 22, 2021",2021,TV-14,58 min,"Documentaries, International Movies",Journalists and fans await Ma Anand Sheela as ...,True
873,s874,Movie,Ahaan,Nikhil Pherwani,"Arif Zakaria, Abuli Mamaji, Niharika Singh, Ra...",India,"May 15, 2021",2021,TV-MA,81 min,"Dramas, Independent Movies, International Movies","Jilted by his wife, a man with OCD finds eye-o...",True
1037,s1038,Movie,Tuesdays & Fridays,Taranveer Singh,"Anmol Thakeria Dhillon, Jhataleka, Niki Walia,...",India,"April 16, 2021",2021,TV-14,106 min,"Comedies, Dramas, International Movies","To avoid the burden of commitment, a young law...",True